version: "2"
run:
  concurrency: 5
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - gocritic
    - govet
    - importas
    - ineffassign
    - nolintlint
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    govet:
      enable:
        - assign
        - errorsas
        - tests
        - unreachable
        - fieldalignment
        - atomic
        - atomicalign
        - bools
        - defers
        - shadow
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
          - staticcheck
        path: _test\.go
      - linters:
          - bodyclose
          - gocritic
          - govet
          - importas
          - ineffassign
          - nolintlint
          - staticcheck
          - unconvert
          - unused
          - usestdlibvars
          - whitespace
        path: graph
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
      - graph
