package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/jalavosus/matomogql/graph/model"
	"github.com/jalavosus/matomogql/matomo"
)

// GetSiteFromID is the resolver for the getSiteFromID field.
func (r *queryResolver) GetSiteFromID(ctx context.Context, idSite int) (*model.Site, error) {
	return matomo.GetSiteFromID(ctx, idSite)
}

// GetSiteURLsFromID is the resolver for the getSiteURLsFromID field.
func (r *queryResolver) GetSiteURLsFromID(ctx context.Context, idSite int) ([]string, error) {
	return matomo.GetSiteURLsFromID(ctx, idSite)
}

// GetSitesWithViewAccess is the resolver for the getSitesWithViewAccess field.
func (r *queryResolver) GetSitesWithViewAccess(ctx context.Context) ([]*model.Site, error) {
	return matomo.GetSitesWithViewAccess(ctx)
}

// GetSitesWithAtLeastViewAccess is the resolver for the getSitesWithAtLeastViewAccess field.
func (r *queryResolver) GetSitesWithAtLeastViewAccess(ctx context.Context) ([]*model.Site, error) {
	return matomo.GetSitesWithAtLeastViewAccess(ctx)
}
