// Code generated by "stringer -type LogAction -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogActionAction-0]
	_ = x[LogActionEvent-1]
	_ = x[LogActionGoal-2]
	_ = x[LogActionEcommerceOrder-3]
	_ = x[logActionUnknown-4]
}

const _LogAction_name = "actioneventgoalecommerceOrderunknown"

var _LogAction_index = [...]uint8{0, 6, 11, 15, 29, 36}

func (i LogAction) String() string {
	if i >= LogAction(len(_LogAction_index)-1) {
		return "LogAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogAction_name[_LogAction_index[i]:_LogAction_index[i+1]]
}
