// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type BrowserInfo struct {
	Family            string  `json:"family"`
	FamilyDescription string  `json:"familyDescription"`
	Browser           string  `json:"browser"`
	Name              string  `json:"name"`
	Icon              *string `json:"icon,omitempty"`
	Code              string  `json:"code"`
	Version           string  `json:"version"`
}

type CampaignInfo struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Keyword   string `json:"keyword"`
	Medium    string `json:"medium"`
	Name      string `json:"name"`
	Source    string `json:"source"`
	Group     string `json:"group"`
	Placement string `json:"placement"`
}

type ConvertedVisitsOptions struct {
	Period    SegmentPeriod `json:"period"`
	StartDate string        `json:"startDate"`
	EndDate   *string       `json:"endDate,omitempty"`
}

type DeviceInfo struct {
	Type                   string  `json:"type"`
	TypeIcon               *string `json:"typeIcon,omitempty"`
	Brand                  string  `json:"brand"`
	Model                  string  `json:"model"`
	OperatingSystem        string  `json:"operatingSystem"`
	OperatingSystemName    string  `json:"operatingSystemName"`
	OperatingSystemIcon    *string `json:"operatingSystemIcon,omitempty"`
	OperatingSystemCode    string  `json:"operatingSystemCode"`
	OperatingSystemVersion string  `json:"operatingSystemVersion"`
	Resolution             *string `json:"resolution,omitempty"`
}

type GetGoalsOptions struct {
	OrderByName *bool `json:"orderByName,omitempty"`
}

type Goal struct {
	IDSite              int             `json:"idsite"`
	IDGoal              int             `json:"idgoal"`
	Name                string          `json:"name"`
	Description         string          `json:"description"`
	MatchAttribute      string          `json:"match_attribute"`
	Pattern             *string         `json:"pattern,omitempty"`
	PatternType         *string         `json:"pattern_type,omitempty"`
	CaseSensitive       *int            `json:"case_sensitive"`
	AllowMultiple       int             `json:"allow_multiple,omitempty"`
	Revenue             int             `json:"revenue"`
	Deleted             int             `json:"deleted"`
	EventValueAsRevenue int             `json:"event_value_as_revenue,omitempty"`
	ConvertedVisits     []*VisitDetails `json:"convertedVisits,omitempty"`
}

type Location struct {
	Continent     string  `json:"continent"`
	ContinentCode string  `json:"continentCode"`
	Country       string  `json:"country"`
	CountryCode   string  `json:"countryCode"`
	CountryFlag   *string `json:"countryFlag,omitempty"`
	Region        string  `json:"region"`
	RegionCode    string  `json:"regionCode"`
	City          string  `json:"city"`
	Location      string  `json:"location"`
	Latitude      string  `json:"latitude"`
	Longitude     string  `json:"longitude"`
}

type OrderByOptions struct {
	Timestamp *OrderBy `json:"timestamp,omitempty"`
}

type Query struct {
}

type ReferrerInfo struct {
	Type              *string `json:"type,omitempty"`
	Name              *string `json:"name,omitempty"`
	Keyword           *string `json:"keyword,omitempty"`
	KeywordPosition   *string `json:"keywordPosition,omitempty"`
	URL               *string `json:"url,omitempty"`
	SearchEngineURL   *string `json:"searchEngineUrl,omitempty"`
	SearchEngineIcon  *string `json:"searchEngineIcon,omitempty"`
	SocialNetworkURL  *string `json:"socialNetworkUrl,omitempty"`
	SocialNetworkIcon *string `json:"socialNetworkIcon,omitempty"`
}

type VisitActionDetails struct {
	Type             string        `json:"type"`
	URL              string        `json:"url"`
	Title            string        `json:"title"`
	Subtitle         string        `json:"subtitle"`
	PageTitle        string        `json:"pageTitle"`
	PageIDAction     int           `json:"pageIdAction"`
	IDPageView       string        `json:"idpageview"`
	ServerTimePretty string        `json:"serverTimePretty"`
	PageID           int           `json:"pageId"`
	TimeSpent        int           `json:"timeSpent"`
	TimeSpentPretty  string        `json:"timeSpentPretty"`
	PageViewPosition int           `json:"pageViewPosition"`
	Timestamp        int           `json:"timestamp"`
	GoalPageID       *int          `json:"goalPageId,omitempty"`
	Referrer         *ReferrerInfo `json:"referrer,omitempty"`
	ReferrerType     *string       `json:"referrerType,omitempty"`
	ReferrerName     *string       `json:"referrerName,omitempty"`
	ReferrerKeyword  *string       `json:"referrerKeyword,omitempty"`
}

type VisitDetails struct {
	IDSite                         int                   `json:"idSite"`
	SiteName                       string                `json:"siteName"`
	SiteCurrency                   string                `json:"siteCurrency"`
	SiteCurrencySymbol             string                `json:"siteCurrencySymbol"`
	IDVisit                        int                   `json:"idVisit"`
	VisitIP                        string                `json:"visitIp"`
	VisitorID                      string                `json:"visitorId"`
	Fingerprint                    string                `json:"fingerprint"`
	VisitServerHour                string                `json:"visitServerHour"`
	GoalConversions                int                   `json:"goalConversions"`
	ActionDetails                  []*VisitActionDetails `json:"actionDetails,omitempty"`
	ServerDate                     string                `json:"serverDate"`
	ServerDatePretty               string                `json:"serverDatePretty"`
	ServerTimestamp                int                   `json:"serverTimestamp"`
	ServerTimePretty               string                `json:"serverTimePretty"`
	FirstActionTimestamp           int                   `json:"firstActionTimestamp"`
	LastActionTimestamp            int                   `json:"lastActionTimestamp"`
	LastActionDateTime             string                `json:"lastActionDateTime"`
	ServerDatePrettyFirstAction    string                `json:"serverDatePrettyFirstAction"`
	ServerTimePrettyFirstAction    string                `json:"serverTimePrettyFirstAction"`
	UserID                         *string               `json:"userId,omitempty"`
	VisitorType                    string                `json:"visitorType"`
	VisitorTypeIcon                *string               `json:"visitorTypeIcon,omitempty"`
	VisitConverted                 int                   `json:"visitConverted"`
	VisitConvertedIcon             *string               `json:"visitConvertedIcon,omitempty"`
	VisitCount                     *int                  `json:"visitCount,omitempty"`
	VisitEcommerceStatus           *string               `json:"visitEcommerceStatus,omitempty"`
	VisitEcommerceStatusIcon       *string               `json:"visitEcommerceStatusIcon,omitempty"`
	DaysSinceFirstVisit            int                   `json:"daysSinceFirstVisit"`
	SecondsSinceFirstVisit         int                   `json:"secondsSinceFirstVisit"`
	DaysSinceLastEcommerceOrder    int                   `json:"daysSinceLastEcommerceOrder"`
	SecondsSinceLastEcommerceOrder *int                  `json:"secondsSinceLastEcommerceOrder,omitempty"`
	VisitDuration                  int                   `json:"visitDuration"`
	VisitDurationPretty            string                `json:"visitDurationPretty"`
	Searches                       int                   `json:"searches"`
	Actions                        int                   `json:"actions"`
	Interactions                   int                   `json:"interactions"`
	LanguageCode                   string                `json:"languageCode"`
	Language                       string                `json:"language"`
	DeviceInfo                     *DeviceInfo           `json:"deviceInfo,omitempty"`
	DeviceType                     string                `json:"deviceType"`
	DeviceTypeIcon                 *string               `json:"deviceTypeIcon,omitempty"`
	DeviceBrand                    string                `json:"deviceBrand"`
	DeviceModel                    string                `json:"deviceModel"`
	OperatingSystem                string                `json:"operatingSystem"`
	OperatingSystemName            string                `json:"operatingSystemName"`
	OperatingSystemIcon            *string               `json:"operatingSystemIcon,omitempty"`
	OperatingSystemCode            string                `json:"operatingSystemCode"`
	OperatingSystemVersion         string                `json:"operatingSystemVersion"`
	Resolution                     *string               `json:"resolution,omitempty"`
	BrowserInfo                    *BrowserInfo          `json:"browserInfo,omitempty"`
	BrowserFamily                  string                `json:"browserFamily"`
	BrowserFamilyDescription       string                `json:"browserFamilyDescription"`
	Browser                        string                `json:"browser"`
	BrowserName                    string                `json:"browserName"`
	BrowserIcon                    *string               `json:"browserIcon,omitempty"`
	BrowserCode                    string                `json:"browserCode"`
	BrowserVersion                 string                `json:"browserVersion"`
	TotalEcommerceRevenue          int                   `json:"totalEcommerceRevenue"`
	TotalEcommerceConversions      int                   `json:"totalEcommerceConversions"`
	TotalEcommerceItems            int                   `json:"totalEcommerceItems"`
	TotalAbandonedCartsRevenue     int                   `json:"totalAbandonedCartsRevenue"`
	TotalAbandonedCarts            int                   `json:"totalAbandonedCarts"`
	TotalAbandonedCartsItems       int                   `json:"totalAbandonedCartsItems"`
	Events                         int                   `json:"events"`
	LocationInfo                   *Location             `json:"locationInfo,omitempty"`
	Continent                      string                `json:"continent"`
	ContinentCode                  string                `json:"continentCode"`
	Country                        string                `json:"country"`
	CountryCode                    string                `json:"countryCode"`
	CountryFlag                    *string               `json:"countryFlag,omitempty"`
	Region                         string                `json:"region"`
	RegionCode                     string                `json:"regionCode"`
	City                           string                `json:"city"`
	Location                       string                `json:"location"`
	Latitude                       string                `json:"latitude"`
	Longitude                      string                `json:"longitude"`
	VisitLocalTime                 string                `json:"visitLocalTime"`
	VisitLocalHour                 string                `json:"visitLocalHour"`
	DaysSinceLastVisit             int                   `json:"daysSinceLastVisit"`
	SecondsSinceLastVisit          int                   `json:"secondsSinceLastVisit"`
	Plugins                        *string               `json:"plugins,omitempty"`
	AdClickID                      string                `json:"adClickId"`
	AdProviderID                   string                `json:"adProviderId"`
	AdProviderName                 string                `json:"adProviderName"`
	FormConversions                int                   `json:"formConversions"`
	SessionReplayURL               *string               `json:"sessionReplayUrl,omitempty"`
	CampaignInfo                   *CampaignInfo         `json:"campaignInfo,omitempty"`
	CampaignID                     string                `json:"campaignId"`
	CampaignContent                string                `json:"campaignContent"`
	CampaignKeyword                string                `json:"campaignKeyword"`
	CampaignMedium                 string                `json:"campaignMedium"`
	CampaignName                   string                `json:"campaignName"`
	CampaignSource                 string                `json:"campaignSource"`
	CampaignGroup                  string                `json:"campaignGroup"`
	CampaignPlacement              string                `json:"campaignPlacement"`
}

type OrderBy string

const (
	OrderByAsc  OrderBy = "ASC"
	OrderByDesc OrderBy = "DESC"
)

var AllOrderBy = []OrderBy{
	OrderByAsc,
	OrderByDesc,
}

func (e OrderBy) IsValid() bool {
	switch e {
	case OrderByAsc, OrderByDesc:
		return true
	}
	return false
}

func (e OrderBy) String() string {
	return string(e)
}

func (e *OrderBy) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderBy", str)
	}
	return nil
}

func (e OrderBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SegmentPeriod string

const (
	SegmentPeriodDay   SegmentPeriod = "Day"
	SegmentPeriodWeek  SegmentPeriod = "Week"
	SegmentPeriodMonth SegmentPeriod = "Month"
	SegmentPeriodRange SegmentPeriod = "Range"
)

var AllSegmentPeriod = []SegmentPeriod{
	SegmentPeriodDay,
	SegmentPeriodWeek,
	SegmentPeriodMonth,
	SegmentPeriodRange,
}

func (e SegmentPeriod) IsValid() bool {
	switch e {
	case SegmentPeriodDay, SegmentPeriodWeek, SegmentPeriodMonth, SegmentPeriodRange:
		return true
	}
	return false
}

func (e SegmentPeriod) String() string {
	return string(e)
}

func (e *SegmentPeriod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SegmentPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SegmentPeriod", str)
	}
	return nil
}

func (e SegmentPeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
